# Aniseed, to have the dotfiles in Fennel
# ---------------------------------------
[[plugins]]
repo = 'Olical/aniseed'
rev = 'v3.9.0'

# Plugin Manager
# --------------
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

# General/Utils
# -------------
[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'

[[plugins]]
repo = 'preservim/nerdcommenter'

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

# File Drawer
# -----------
[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

# VCS Sign Info
# -------------
[[plugins]]
repo = 'mhinz/vim-signify'

# Status Line
# -----------
[[plugins]]
repo = 'itchyny/lightline.vim'

# Buffer Line
# -----------
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'romgrk/barbar.nvim'
depends = 'nvim-web-devicons'

# Fuzzy Finder
# ------------
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'antoinemadec/coc-fzf'
depends = ['fzf', 'coc.nvim']
rev = 'release'

[[plugins]]
repo = 'stsewd/fzf-checkout.vim'
depends = ['fzf', 'vim-fugitive']

# Completions
# -----------
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = 0

[[plugins]]
repo = 'neoclide/coc-tsserver'
depends = 'coc.nvim'
merged = 0
build = 'yarn install --frozen-lockfile'

[[plugins]]
repo = 'neoclide/coc-eslint'
depends = 'coc.nvim'
merged = 0
build = 'yarn install --frozen-lockfile'

[[plugins]]
repo = 'neoclide/coc-prettier'
depends = 'coc.nvim'
merged = 0
build = 'yarn install --frozen-lockfile'

[[plugins]]
repo = 'neoclide/coc-json'
depends = 'coc.nvim'
merged = 0
build = 'yarn install --frozen-lockfile'

[[plugins]]
repo = 'neoclide/coc-vetur'
depends = 'coc.nvim'
merged = 0
build = 'yarn install --frozen-lockfile'

[[plugins]]
repo = 'neoclide/coc-solargraph'
depends = 'coc.nvim'
merged = 0
build = 'yarn install --frozen-lockfile'

[[plugins]]
repo = 'fannheyward/coc-rust-analyzer'
depends = 'coc.nvim'
merged = 0
build = 'yarn install --frozen-lockfile'

[[plugins]]
repo = 'josa42/coc-lua'
depends = 'coc.nvim'
merged = 0
build = 'yarn install --frozen-lockfile'

# Languages
# ---------
[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
merged = 0

[[plugins]]
repo = 'bakpakin/fennel.vim'

[[plugins]]
repo = 'euclidianAce/BetterLua.vim'

# Colors
# ------
[[plugins]]
repo = '~/OneDrive/Tools/DraculaPro/themes/vim'
name = 'dracula_pro'
merged = 0
